version: "3.8"

networks:
  thmar-apps:
    name: thmar-apps # تثبيت اسم الشبكة في دوكر عشان الملفات التانية تشوفها
    driver: bridge

volumes:
  db-data:
  odoo-web-data:

# إعداد الـ Logging لتقليل حجم الـ Logs وحماية مساحة السيرفر
x-logging: &default-logging
  options:
    max-size: "50m"
    max-file: "3"
  driver: json-file

services:
  pg-db:
    image: postgres:15
    container_name: pg-db
    logging: *default-logging
    environment:
      - POSTGRES_USER=odoo19
      - POSTGRES_PASSWORD=odoo19
    ports:
      - "5433:5432"
    networks:
      - thmar-apps
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  odoo:
    build: .
    container_name: odoo
    logging: *default-logging
    depends_on:
      - pg-db
    ports:
      - "8019:8069"
      - "8072:8072"
    environment:
      - HOST=pg-db
      - USER=odoo19
      - PASSWORD=odoo19
    command: odoo
    volumes:
      - ./etc:/etc/odoo
      - ../../../enterprise-19.0:/mnt/enterprise_addons
      - ../../:/mnt/thamar_hr_project
      - ../../../thmar_dani:/mnt/custom_addons
      - odoo-web-data:/var/lib/odoo
    networks:
      - thmar-apps
    restart: always