# -*- coding: utf-8 -*-
"""Leave allocation engine for Egyptian labor law compliance.

Handles:
- Dynamic annual leave entitlement computation
- Auto-generation of casual + annual allocations
- Yearly cron for recomputation, carryover, and new allocations
"""
import logging
from datetime import date

from dateutil.relativedelta import relativedelta

from odoo import api, fields, models, _

_logger = logging.getLogger(__name__)

# ── Constants ──
CASUAL_DAYS = 7
ANNUAL_BASE_STANDARD = 14
ANNUAL_FIRST_YEAR_EARLY = 14    # hired before September
ANNUAL_FIRST_YEAR_LATE = 8      # hired September or later
FIRST_YEAR_CUTOFF_MONTH = 9     # September
AGE_BONUS_THRESHOLD = 50        # years old
AGE_BONUS_DAYS = 9
EXPERIENCE_BONUS_THRESHOLD = 10  # total service years
EXPERIENCE_BONUS_DAYS = 9
HAZARDOUS_BONUS_DAYS = 7


class HrLeaveAllocation(models.Model):
    _inherit = 'hr.leave.allocation'

    # ── Tracking fields ──
    is_auto_generated = fields.Boolean(
        string='Auto-Generated',
        default=False,
        readonly=True,
        help="Indicates this allocation was auto-generated by the leave management system.",
    )
    leave_year = fields.Integer(
        string='Leave Year',
        readonly=True,
        help="The calendar year this allocation applies to.",
    )

    # ================================================================
    # PUBLIC API: Entitlement Computation
    # ================================================================

    @api.model
    def _compute_employee_entitlement(self, employee, reference_date=None):
        """Compute the full annual leave entitlement breakdown for an employee.

        Returns a dict with all entitlement details for transparency.

        :param employee: hr.employee or hr.employee.public recordset (single)
        :param reference_date: date to compute against (defaults to today)
        :return: dict with entitlement breakdown
        """
        if reference_date is None:
            reference_date = fields.Date.today()

        # ── Age ──
        age = 0
        if employee.birthday:
            age = relativedelta(reference_date, employee.birthday).years

        # ── Service years ──
        contract_start = employee.contract_date_start
        current_service_years = 0.0
        if contract_start:
            delta = relativedelta(reference_date, contract_start)
            current_service_years = round(delta.years + delta.months / 12.0, 2)

        external_years = employee.external_experience_years or 0.0
        total_service_years = round(current_service_years + external_years, 2)

        # ── Base annual days ──
        base_days = ANNUAL_BASE_STANDARD  # default: 14 days
        if contract_start and contract_start.year == reference_date.year:
            # First year of service — prorated
            if contract_start.month >= FIRST_YEAR_CUTOFF_MONTH:
                base_days = ANNUAL_FIRST_YEAR_LATE  # 8 days
            else:
                base_days = ANNUAL_FIRST_YEAR_EARLY  # 14 days

        # ── Bonuses (cumulative per user confirmation) ──
        age_bonus = AGE_BONUS_DAYS if age >= AGE_BONUS_THRESHOLD else 0
        experience_bonus = EXPERIENCE_BONUS_DAYS if total_service_years >= EXPERIENCE_BONUS_THRESHOLD else 0
        hazardous_bonus = HAZARDOUS_BONUS_DAYS if employee.is_hazardous_location else 0

        total_annual = base_days + age_bonus + experience_bonus + hazardous_bonus

        return {
            'age': age,
            'current_service_years': current_service_years,
            'total_service_years': total_service_years,
            'base_days': base_days,
            'age_bonus': age_bonus,
            'experience_bonus': experience_bonus,
            'hazardous_bonus': hazardous_bonus,
            'total_annual': total_annual,
            'casual_days': CASUAL_DAYS,
        }

    # ================================================================
    # AUTO-ALLOCATION: Generate allocations for a single employee
    # ================================================================

    @api.model
    def _generate_employee_allocations(self, employee, year=None, carryover_days=0.0):
        """Generate Casual + Annual leave allocations for a given employee and year.

        :param employee: hr.employee record (single)
        :param year: calendar year (defaults to current year)
        :param carryover_days: annual leave days carried over from previous year
        """
        if year is None:
            year = fields.Date.today().year

        annual_type = self._get_annual_leave_type(employee.company_id)
        casual_type = self._get_casual_leave_type(employee.company_id)

        if not annual_type and not casual_type:
            _logger.warning(
                "No annual or casual leave types configured for company %s. "
                "Skipping allocation for employee %s.",
                employee.company_id.name, employee.name,
            )
            return

        reference_date = date(year, 12, 31)  # Compute entitlement as of end of year
        details = self._compute_employee_entitlement(employee, reference_date)

        # ── Casual Leave Allocation ──
        if casual_type:
            self._create_casual_allocation(employee, casual_type, year, details)

        # ── Annual Leave Allocation ──
        if annual_type:
            self._create_annual_allocation(employee, annual_type, year, details, carryover_days)

    @api.model
    def _create_casual_allocation(self, employee, leave_type, year, details):
        """Create a fixed-duration casual leave allocation for the year.

        Casual leave: 7 days, valid Jan 1 – Dec 31, no carryover.
        """
        # Check if allocation already exists for this year
        existing = self.search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', leave_type.id),
            ('is_auto_generated', '=', True),
            ('leave_year', '=', year),
            ('state', '!=', 'refuse'),
        ], limit=1)

        if existing:
            _logger.info(
                "Casual allocation already exists for %s in %d, skipping.",
                employee.name, year,
            )
            return existing

        notes = (
            "Auto-generated Casual Leave allocation.\n"
            "Year: %d\n"
            "Entitlement: %d days\n"
            "Rule: Fixed 7 days/year, non-carryover, expires Dec 31."
        ) % (year, CASUAL_DAYS)

        allocation = self.sudo().create({
            'employee_id': employee.id,
            'holiday_status_id': leave_type.id,
            'number_of_days': CASUAL_DAYS,
            'date_from': date(year, 1, 1),
            'date_to': date(year, 12, 31),
            'notes': notes,
            'allocation_type': 'regular',
            'is_auto_generated': True,
            'leave_year': year,
        })

        # Note: allocation_validation_type='no_validation' on the leave type
        # means Odoo auto-approves the allocation on create.

        allocation.message_post(
            body=_(
                "🗓️ <b>Casual Leave Allocation – %(year)d</b><br/>"
                "Entitlement: <b>%(days)d days</b><br/>"
                "Valid: Jan 1 – Dec 31, %(year)d<br/>"
                "Non-carryover: expires automatically on Dec 31.",
                year=year,
                days=CASUAL_DAYS,
            ),
            message_type='comment',
            subtype_xmlid='mail.mt_note',
        )

        _logger.info(
            "Created casual allocation: %d days for %s (%d)",
            CASUAL_DAYS, employee.name, year,
        )
        return allocation

    @api.model
    def _create_annual_allocation(self, employee, leave_type, year, details, carryover_days=0.0):
        """Create a monthly accrual annual leave allocation for the year.

        Uses Odoo's accrual plan framework to drip-feed days monthly.
        """
        # Check if allocation already exists for this year
        existing = self.search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', leave_type.id),
            ('is_auto_generated', '=', True),
            ('leave_year', '=', year),
            ('state', '!=', 'refuse'),
        ], limit=1)

        if existing:
            _logger.info(
                "Annual allocation already exists for %s in %d, skipping.",
                employee.name, year,
            )
            return existing

        total_annual = details['total_annual']
        total_with_carryover = total_annual + carryover_days

        # ── Build the computation breakdown for audit trail ──
        notes_lines = [
            "Auto-generated Annual Leave allocation.",
            "Year: %d" % year,
            "",
            "─── Entitlement Breakdown ───",
            "Base annual days: %.1f" % details['base_days'],
        ]
        if details['age_bonus']:
            notes_lines.append(
                "Age bonus (50+, age=%d): +%.1f days" % (details['age'], details['age_bonus'])
            )
        if details['experience_bonus']:
            notes_lines.append(
                "Experience bonus (10+ years, total=%.1f): +%.1f days" % (
                    details['total_service_years'], details['experience_bonus']
                )
            )
        if details['hazardous_bonus']:
            notes_lines.append(
                "Hazardous location bonus: +%.1f days" % details['hazardous_bonus']
            )
        notes_lines.append("Total new entitlement: %.1f days" % total_annual)
        if carryover_days:
            notes_lines.append("Carried over from previous year: +%.1f days" % carryover_days)
            notes_lines.append("Grand total: %.1f days" % total_with_carryover)
        notes_lines.append("")
        if leave_type.use_monthly_accrual:
            monthly_rate = total_with_carryover / 12.0
            notes_lines.append("Allocation type: Monthly Accrual")
            notes_lines.append("Monthly accrual rate: %.2f days/month" % monthly_rate)
            notes_lines.append("Policy: Balance accrues monthly. Employees cannot")
            notes_lines.append("        take more than their accrued balance.")
        else:
            notes_lines.append("Allocation type: Regular (full balance upfront)")

        notes = "\n".join(notes_lines)

        allocation = self.sudo().create({
            'employee_id': employee.id,
            'holiday_status_id': leave_type.id,
            'number_of_days': total_with_carryover,
            'date_from': date(year, 1, 1),
            'date_to': False,  # No expiry — unlimited carryover
            'notes': notes,
            'allocation_type': 'regular',
            'is_auto_generated': True,
            'leave_year': year,
        })

        # Note: allocation_validation_type='no_validation' on the leave type
        # means Odoo auto-approves the allocation on create.

        # ── Post detailed chatter message ──
        body_parts = [
            _("📋 <b>Annual Leave Allocation – %(year)d</b><br/>", year=year),
            _("<b>Base:</b> %(base).1f days<br/>", base=details['base_days']),
        ]
        if details['age_bonus']:
            body_parts.append(
                _("<b>Age 50+ bonus:</b> +%(bonus).1f days (age: %(age)d)<br/>",
                  bonus=details['age_bonus'], age=details['age'])
            )
        if details['experience_bonus']:
            body_parts.append(
                _("<b>Experience 10+ years bonus:</b> +%(bonus).1f days (total service: %(svc).1f yrs)<br/>",
                  bonus=details['experience_bonus'], svc=details['total_service_years'])
            )
        if details['hazardous_bonus']:
            body_parts.append(
                _("<b>Hazardous location bonus:</b> +%(bonus).1f days<br/>",
                  bonus=details['hazardous_bonus'])
            )
        body_parts.append(
            _("<b>New entitlement:</b> %(total).1f days<br/>", total=total_annual)
        )
        if carryover_days:
            body_parts.append(
                _("<b>Carryover:</b> +%(carry).1f days<br/>", carry=carryover_days)
            )
            body_parts.append(
                _("<b>Grand total:</b> %(grand).1f days<br/>", grand=total_with_carryover)
            )
        if leave_type.use_monthly_accrual:
            monthly_rate = total_with_carryover / 12.0
            body_parts.append(
                _("<br/>📊 <b>Monthly Accrual Policy Active</b><br/>"
                  "Rate: <b>%(rate).2f days/month</b><br/>"
                  "Employees can only use accrued balance up to the current month.",
                  rate=monthly_rate)
            )

        allocation.message_post(
            body="".join(body_parts),
            message_type='comment',
            subtype_xmlid='mail.mt_note',
        )

        _logger.info(
            "Created annual allocation: %.1f days (%.1f new + %.1f carryover) for %s (%d)",
            total_with_carryover, total_annual, carryover_days, employee.name, year,
        )
        return allocation

    # ================================================================
    # YEARLY CRON JOB
    # ================================================================

    @api.model
    def _cron_yearly_leave_recompute(self):
        """Yearly cron job (Jan 1) to recompute and regenerate all leave allocations.

        Steps:
        1. Determine the new year and previous year
        2. For each active employee:
           a. Calculate remaining annual leave from previous year (carryover)
           b. Generate new casual allocation (7 days, valid current year only)
           c. Generate new annual allocation with carryover balance added
        3. Log all computation details
        """
        today = fields.Date.today()
        new_year = today.year
        prev_year = new_year - 1

        _logger.info(
            "═══ Starting yearly leave recompute for %d ═══", new_year,
        )

        employees = self.env['hr.employee'].search([
            ('active', '=', True),
            ('company_id', '!=', False),
        ])

        _logger.info("Processing %d active employees...", len(employees))

        success_count = 0
        error_count = 0

        for employee in employees:
            try:
                # ── Step 1: Calculate carryover from previous year ──
                carryover = self._compute_annual_carryover(employee, prev_year)

                # ── Step 2: Generate new year allocations ──
                self._generate_employee_allocations(
                    employee,
                    year=new_year,
                    carryover_days=carryover,
                )
                success_count += 1
            except Exception as e:
                error_count += 1
                _logger.error(
                    "Failed to process leave recompute for employee %s (ID: %s): %s",
                    employee.name, employee.id, e,
                )

        _logger.info(
            "═══ Yearly leave recompute completed: %d success, %d errors ═══",
            success_count, error_count,
        )

    @api.model
    def _compute_annual_carryover(self, employee, prev_year):
        """Compute remaining annual leave days to carry over from previous year.

        Carryover is unlimited (per user specification).

        :param employee: hr.employee record
        :param prev_year: the previous calendar year
        :return: float — number of days to carry over
        """
        annual_type = self._get_annual_leave_type(employee.company_id)
        if not annual_type:
            return 0.0

        # Find all approved annual allocations for the previous year
        prev_allocations = self.search([
            ('employee_id', '=', employee.id),
            ('holiday_status_id', '=', annual_type.id),
            ('state', '=', 'validate'),
            ('leave_year', '=', prev_year),
        ])

        if not prev_allocations:
            # Also check for allocations without leave_year (legacy or manually created)
            prev_allocations = self.search([
                ('employee_id', '=', employee.id),
                ('holiday_status_id', '=', annual_type.id),
                ('state', '=', 'validate'),
                ('date_from', '>=', date(prev_year, 1, 1)),
                ('date_from', '<=', date(prev_year, 12, 31)),
                ('leave_year', '=', False),
            ])

        if not prev_allocations:
            return 0.0

        # Get consumed leaves data for the previous year
        total_allocated = sum(prev_allocations.mapped('number_of_days'))
        target_date = date(prev_year, 12, 31)

        try:
            consumed_data = employee._get_consumed_leaves(annual_type, target_date)[0]
            total_taken = 0.0
            for alloc, data in consumed_data[employee][annual_type].items():
                if alloc in prev_allocations:
                    total_taken += data.get('leaves_taken', 0.0)
        except Exception as e:
            _logger.warning(
                "Error computing consumed leaves for %s in %d: %s. "
                "Falling back to simple allocation count.",
                employee.name, prev_year, e,
            )
            # Fallback: count approved leaves manually
            leaves = self.env['hr.leave'].search([
                ('employee_id', '=', employee.id),
                ('holiday_status_id', '=', annual_type.id),
                ('state', '=', 'validate'),
                ('date_from', '>=', fields.Datetime.to_datetime(date(prev_year, 1, 1))),
                ('date_to', '<=', fields.Datetime.to_datetime(date(prev_year, 12, 31))),
            ])
            total_taken = sum(leaves.mapped('number_of_days'))

        remaining = max(0.0, total_allocated - abs(total_taken))

        _logger.info(
            "Annual carryover for %s from %d: allocated=%.1f, taken=%.1f, remaining=%.1f",
            employee.name, prev_year, total_allocated, abs(total_taken), remaining,
        )

        return remaining

    # ================================================================
    # HELPER METHODS
    # ================================================================

    @api.model
    def _get_annual_leave_type(self, company=None):
        """Find the leave type marked as Annual Leave."""
        domain = [('is_annual_leave', '=', True)]
        if company:
            domain.append(('company_id', 'in', [company.id, False]))
        return self.env['hr.leave.type'].search(domain, limit=1)

    @api.model
    def _get_casual_leave_type(self, company=None):
        """Find the leave type marked as Casual Leave."""
        domain = [('is_casual_leave', '=', True)]
        if company:
            domain.append(('company_id', 'in', [company.id, False]))
        return self.env['hr.leave.type'].search(domain, limit=1)
