name: Deploy Odoo 19 to Local Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # التغيير السحري هنا: بنقول لجيتهاب شغل الـ Job دي على السيرفر المحلي بتاعي
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Update Odoo Containers
        run: |
          echo "============ بدء عملية الـ Deployment المحلية ============"
          
          # 1. الدخول لمجلد المشروع (اضبط المسار حسب مكانه الفعلي على السيرفر)
          cd ~/Documents/odoo19/thamar_hr_project
          
          # 2. سحب الكود الجديد
          git pull origin master
          
          # 3. بناء وتحديث دوكر
          docker compose up -d --build
          
          # 4. ترقية الموديولات
          docker compose exec -d odoo odoo -u all --stop-after-init
          
          echo "============ تم التحديث بنجاح داخلياً! 🚀 ============"
